version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - docker login --username anilkumar1529 --password anil@1234
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      #$(aws ecr get-login --no-include-email $ap-south-1)
      - REPOSITORY_URI=245324908369.dkr.ecr.us-east-1.amazonaws.com/test:latest
      #COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-17)
      #IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest 245324908369.dkr.ecr.us-east-1.amazonaws.com/test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #docker push $REPOSITORY_URI:latest
      #docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push 245324908369.dkr.ecr.us-east-1.amazonaws.com/test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"test","imageUri":"%s"}]' 245324908369.dkr.ecr.us-east-1.amazonaws.com/test:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
